### ISSUE TITLE
【189】【讨论】 我是标题,修改我,拷贝链接到下方https://neucrack.com/p/189

### ISSUE THREAD

**Issue by laikee99** [neucrack/web#1]
文章链接：
https://neucrack.com/p/189
----------------------------------------------------------------------------------------------------------------------------

## 主题简述
希望了解如何低成本实现红外温度检测

## 正文
博主好，我想了解下如何不用如此高昂的设备实现测温呢？

**Comment by suyonob20** [comment]
Hi , I will try your tutor but not succesfull, do you have wire  mlx90640 to sipeed maixbit?

**Comment by suyonob20** [comment]
Hi , I have try your tutor but  unsuccessfull,  do you have wire mlx90640 to sipeed maaixbit?

**Comment by Neutree** [comment]
@sddwt 低成本用点式测温就好了 就是市面上那些测温枪

**Comment by Neutree** [comment]
@suyonob20 In this tutor the MLX90640 is a serial module, just connect to maixbit's io9 and io10
![image](https://user-images.githubusercontent.com/8625829/116248782-b8adc780-a79e-11eb-989d-f14f07b5c6bc.png)

**Comment by suyonob20** [comment]
![mlx90640](https://user-images.githubusercontent.com/67845211/116867666-bed8f380-ac37-11eb-8e0c-b4c284a0c477.jpg)

Thank you for your answere,   but the problem is my sensor  mlx 90640 doesn;t have  pin TX and RX, it has i2c pin (SDA  and SCL),  do you have any idea?

**Comment by suyonob20** [comment]
Thank you for your answere, but the problem is my sensor mlx 90640 doesn;t have pin TX and RX, it has i2c pin (SDA and SCL), do you have any idea?

![image](https://user-images.githubusercontent.com/67845211/116868981-ffd20780-ac39-11eb-92e9-4d5b4d350787.png)

**Comment by Neutree** [comment]
the demo in this post just used the serial module, but yours is IIC module, you have to write or find a driver for it
