### ISSUE TITLE
【342】【讨论】 我是标题,修改我,拷贝链接到下方https://neucrack.com/p/342

### ISSUE THREAD

**Issue by LX2035** [neucrack/web#2]
文章链接：
https://neucrack.com/p/342

----------------------------------------------------------------------------------------------------------------------------

## 主题简述

您好，不太清楚这个工具具体是如何使用的，网上也找不到其他相关资料，希望能提供进一步帮助

## 正文

这里写正文，尽量描述清楚，可以贴截图、链接、附件等

**Comment by Neutree** [comment]
@LX2035 看这个文档 https://teedoc.github.io/  

其实就是一个 python 写的软件，和用常规的python 软件一样 
比如可以这样用
先克隆一个模板文档
```
git clone https://github.com/teedoc/teedoc.github.io.git my_doc
cd my_doc
```
* 安装软件
```
pip3 install teedoc
```
* 然后安装插件
```
teedoc install
```
* 然后预览
```
teedoc serve
```
打开浏览器访问 http://127.0.0.1:2333

**Comment by Neutree** [comment]
看这里 ： https://teedoc.github.io/get_started/zh/install/index.html
