### ISSUE TITLE
【358】【讨论】 pytorch hub 403 问题

### ISSUE THREAD

**Issue by junhuanchen** [neucrack/web#3]
文章链接：
https://neucrack.com/p/358

----------------------------------------------------------------------------------------------------------------------------

## 主题简述

pytorch hub 403 问题

## 正文

torch.hub._validate_not_a_forked_repo=lambda a,b,c: True

https://github.com/pytorch/pytorch/issues/61755

**Comment by Neutree** [comment]
好 非常好
