### ISSUE TITLE
【286】【勘误】 网络代理地址有误

### ISSUE THREAD

**Issue by qisanchi** [neucrack/web#4]
文章链接：

https://neucrack.com/p/286

----------------------------------------------------------------------------------------------------------------------------

## 问题简述

二 build 镜像时使用代理

这一节中代码块的本地网络代理地址书写有误 

## 正文
```
docker build --build-arg http_proxy=http://172.17.0.0.1:8123 --build-arg https_proxy=http://172.17.0.0.1:8123 -t image_name .
```
应该将其中的 **172.17.0.0.1** 改为 **172.17.0.1**
![image](https://user-images.githubusercontent.com/63494524/168455415-e05075ca-8cbe-45f6-b75a-f6b3ccd942be.png)

**Comment by Neutree** [comment]
ok 谢啦 改好了
