### ISSUE TITLE
【466】【讨论】 KODI是使用GDM还是lightdm还是wayland问题讨论

### ISSUE THREAD

**Issue by tangzhi1996** [neucrack/web#6]
文章链接：

https://neucrack.com/p/466

----------------------------------------------------------------------------------------------------------------------------

## 主题简述
关于这句话
需要在 lightdm 或者 gdm 或者 wayland 窗口模式下运行，即开机登录时选择 kodi 或者 wayland

这里写内容简述，尽量少于200字

在你描述armbian系统下,安装KODI,并启用硬解码,的问题上,倒是是使用 lightdm 或者 gdm 或者 wayland            和 文章中前文写到了 gdm 或者 wayland  没有提到lightdm,按照你的方案,我已经在debian系统下,mpv 测试硬解码OK,无报错,KODI,下我不确定是否是硬解码,
系统环境是debian+lightdm +xfce4,运行在rock5b硬件上

## 正文

这里写正文，尽量描述清楚，可以贴截图、链接、附件等

**Comment by Neutree** [comment]
@tangzhi1996 kodi在系统信息里面看，默认就是用gbm
