### ISSUE TITLE
【466】【讨论】 CAPI yolov5的例程算力似乎已经没问题了

### ISSUE THREAD

**Issue by KevlarKanou** [neucrack/web#7]
文章链接：
https://neucrack.com/p/466

----------------------------------------------------------------------------------------------------------------------------

## 主题简述

CAPI yolov5的例程算力似乎已经没问题了

## 正文

rknn_yolov5_demo跑了一下，10次平均23.4ms。默认是单核NPU，开三核会报错，原因可能是转换模型的toolkit2版本太旧（https://t.rock-chips.com/forum.php?mod=viewthread&tid=4355），之后再重新转换试一下

**Comment by Neutree** [comment]
那很好哦 估计有优化了
