### ISSUE TITLE
关于将MLX90640连接到MAIX开发板上的一些问题

### ISSUE THREAD

**Issue by DOCTORWU1080** [neucrack/web#8]
文章链接：
https://neucrack.com/p/189

----------------------------------------------------------------------------------------------------------------------------

## 主题简述
关于将MLX90640应用于maixduino的一些问题。

这里写内容简述，尽量少于200字
您好，我正在尝试做将mlx90640连接到maxiduino上并且尝试出图。来采集数据并且做识别训练。

## 正文
您好，我是初次使用maix开发板的新手，尝试将您的程序在我的开发板上运行起来，在尝试用maix py调试的时候发现maixpy会占用      I 2C接口，使我无法调试程序。所以我将他打包成为一个上电自动运行的脚本boot.py。但是程序无法正常运行。
具体引脚如下
MLX90640　　　maixduino
VIN                       VIN
GND　                  GND
RX　　　　　　　TX
TX　　　　　　　RX
SCL　　　　　　SCL
SDA　　　　　　SDA
NC　　　　　　悬空
PS　　　　　　　GND
注：这里PS接GND是我根据90640的手册上写的把模块 PS 接 GND 或者 SET 点焊
接上，模块本身 MCU 不工作，可以经过 I2C 直接操作 MLX90640。

目前情况是，上电之后，LCD屏幕闪烁，随后没有反应了。所以在这里想要请教以下大佬，如何能让探头正常工作。
谢谢大佬
这里写正文，尽量描述清楚，可以贴截图、链接、附件等

**Comment by Neutree** [comment]
你这问题过于大了，没法回答，关闭咯。建议自己多调试
