### ISSUE TITLE
【384】【讨论】 usage_v831_ttyS1.py链接失效

### ISSUE THREAD

**Issue by windskyxb** [neucrack/web#9]
文章链接：

https://neucrack.com/p/384

----------------------------------------------------------------------------------------------------------------------------

## 主题简述

链接失效

## 正文

https://github.com/sipeed/MaixPy3/blob/master/examples/maix_v831/usage/usage_v831_ttyS1.py
这个链接的文件404了，请问还有这个文件的代码吗？
![image](https://github.com/neucrack/web/assets/60282327/5b49e518-4dc3-4983-b21b-3968295080bc)

**Comment by Neutree** [comment]
@windskyxb  https://github.com/sipeed/MaixPy3/blob/release/tests/maix_v831/usage_v831_ttyS1.py

**Comment by windskyxb** [comment]
> @windskyxb https://github.com/sipeed/MaixPy3/blob/release/tests/maix_v831/usage_v831_ttyS1.py

感谢！
